### PR TITLE
add 11ty navigation, improve menu accessibility

### PR DESCRIPTION
**Pull request by trujic1000**
Not sure how you handle less/css, but I added a class "visually-hidden" to your menu button. It's used to hide the text from the page, but it's there for assistive technology. Add this utility class wherever you think is appropriate:
```
.visually-hidden:not(:focus):not(:active) {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  clip-path: inset(50%);
  white-space: nowrap;
}
```

### CODE REVIEW

**Comment by ItsEthanH** [comment]
> Do you know how to set this up to support a submenu structure?

You can use the "parent" key under the eleventyNavigation section in the frontmatter.
See: https://www.11ty.dev/docs/plugins/navigation/#example

**Comment by ItsEthanH** [comment]
Going to merge this and create a new branch with all the feedback we've received. Thank you for this! Stay tuned for v4.1 :)

**Comment by monkeywhovapes** [comment]
Cool beans. What's part of the v4.1 update?

@ItsEthanH , I saw your fork and don't think the image aspect of the script is working. It's not creating a new folder into /public. Maybe I am doing something wrong. I'll drop a file in /src/images/...jpg (and webp)... reference to it in html code and it's not being saved into /public/images.
Also, quick question while on this, why is it going to /images and not /assets/images? (is this a best practice technique?)

Thanks in advance!

**Comment by ItsEthanH** [comment]
Lots of cool things, using the feedback from Citrous' announcement thread!

- Improved navigation from this PR
- An overhaul to images, making them responsive and served in next-gen formats
- A centralised store of data to get the template up and running quicker
- General tidying up and file structure changes
- A big ole README update to account for the above

May I ask what fork you're referring to? I'm not too sure I've done a fork of this 😅 I have a personal starter kit that I made to test the above features out, but I'll be using this when I've finished the update.

So the change from /images to /asset/images will be fully explained in the new README, but there's two reasons for this.

1. I'm having issues with the eleventy image plugin to read images from /assets/images. It will either not move the images to public, or move all the source images to public. This is not what we want. Instead, we now have /images to store the source images, and eleventy will read, optimise then convert into production images in /public/images.

2. There are some images which people may not want optimised. This is particularly true for the header logo in this kit. These images belong in /assets/images, where it is included in the /assets passthrough in the config file.

Hope this all makes sense. I'm planning on releasing this either tonight or tomorrow morning (GMT), but if there's anything else you need, I'm more than happy to reply :)

**Comment by monkeywhovapes** [comment]
Very exciting. Both the new nav structure and the image optimization will be a game-changer for this kit.

I was referring to your personal starter kit (https://github.com/ItsEthanH/ehwd-starter). I had a chance to test it and loved the simplicity but just couldn't figure out the image aspect of it. Currently, I am using v4 for a client and spent over an hour (manually) optimizing the images... i need to cut this time-consuming activity out of my workflow lol. 

As you going to use sass or continue with less? I noticed in your kit, you were using sass (and sass compiler, etc).

I'm on discord if you wanna chat more about these kits; BadlandsCoder#7119

**Comment by ItsEthanH** [comment]
I'll post this here, as there are some very good information everyone could do with, but I'll add you discord after :)

The images utilises shortcodes. The image shortcode in my kit is the one I'm working on for this one. The syntax is as follows

`{% image 'IMAGE SOURCE', 'ALT TEXT', 'PICTURE ELEMENT CLASS', 'LAZY/EAGER LOADING', 'IMG MEDIA QUERY'%}`

Replace each capilitised string with what it says (keep the quotes), and you'll get a fully responsive, optimised image which will serve in a next-gen webp format. As images are the main culprit of poor-performing websites, the idea with this is to get near perfect scores out of the box with this shortcode/kit.

That hour you spent will be the last one. It's liberating, trust me.

As for SASS, that's a personal choice. I've always used SASS simply because the internet told me it was better, and have stuck with it since. Maybe in v4.2 we can add css/less/sass options in it? That brings difficulties in differing package.jsons, file structures, so I'd have to think more about it.

**Pull request merged**
